config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :goals, except: [:show, :index]

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :goal_title, :completion, :user_id, presence: true
  validates :hidden, inclusion: [true, false]

  belongs_to :user,
    foreign_key: :user_id,
    primary_key: :id,
    class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  attr_reader :password
  after_initialize :ensure_session_token

  has_many :goals,
    foreign_key: :user_id,
    primary_key: :id,
    class_name: "Goal"

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def self.find_by_credentials(username, password)
    juser = User.find_by(username: username)
    return nil unless juser && juser.is_password?(password)
    juser
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def login!(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def logout
    session[:session_token] = nil
    @current_user = nil
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    # @goal = current_user.goals.new(goal_params)
    @goal.completion = 0
    if @goal.save
      redirect_to user_url(@goal.user_id)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])

    if @goal.update(goal_params)
      redirect_to user_url(@goal.user_id)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    goal = Goal.find(params[:id])
    goal.destroy
    redirect_to user_url(goal.user_id)
  end


  private
    def goal_params
      params.require(:goal).permit(:goal_title, :hidden, :completion)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user
      login!(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @users_goals = @user.goals
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>".html_safe
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/edit.html.erb
<h3>Update Your Goal</h3>
<% flash.each do |notice| %>
  <p><%= notice %>
<% end %>

<form class="" action="<%= goal_url(@goal) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>

  <label>
    Goal
    <input type="text" name="goal[goal_title]" value="<%= @goal.goal_title %>">
  </label>

  <label>
    Goal Type
    <select class="" name="goal[hidden]">
      <option value="<%= true %>" <% if @goal.hidden %>selected<% end %>>Private</option>
      <option value="<%= false %>" <% if !@goal.hidden %>selected<% end %>>Public</option>
    </select>
  </label>

  <label>
    Progress Percentage
    <input type="text" name="goal[completion]" value=" <%= @goal.completion %>">
  </label>

  <input type="submit" value="Update Goal">

</form>

app/views/goals/new.html.erb
<h3>Create a New Goal</h3>
<% flash.each do |notice| %>
  <p><%= notice %>
<% end %>

<form class="" action="<%= goals_url %>" method="post">
  <%= auth_token %>

  <label>
    Goal
    <input type="text" name="goal[goal_title]" value="">
  </label>

  <label>
    Goal Type
    <select class="" name="goal[hidden]">
      <option value="<%= true %>">Private</option>
      <option value="<%= false %>">Public</option>
    </select>
  </label>

  <input type="submit" value="Set Goal">

</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<% if logged_in? %>
  <%= button_to "Sign out", session_url, method: :delete %>
<% end %>

</body>
</html>

app/views/users/_buttons.html.erb
<%= button_to "Edit Goal", edit_goal_url(goal), method: :get %>
<%= button_to "Delete Goal", goal_url(goal), method: :delete %>

app/views/users/_goal_guts.html.erb
<h3><%= goal.goal_title %></h3>
<span style="<%= goal.completion == 100 ? "color:#00FF00" : "" %>">
  Progress:
  <br>
  <% goal.completion.times do |percentage| %>
    |
  <% end %>
</span>

app/views/users/new.html.erb
<h3>New user</h3>

<form class="" action="<%= users_url %>" method="post">
  <%= auth_token %>

  <label>Username
    <input type="text" name="user[username]" value="">
  </label>

  <label>
    Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" name="name" value="Create User">
</form>

app/views/users/show.html.erb
<!-- TODO: goal partial -->
<h1><%= "#{@user.username}'s goals" %></h1>
  <h3>My Public Goals</h3>
<% @users_goals.each do |goal| %>
  <% next if goal.hidden == true %>
  <%= render "goal_guts", goal: goal %>
  <% if @user == current_user %>
    <%= render "buttons", goal: goal %>
  <% end %>
<% end %>
<% if @user == current_user %>
  <% if @users_goals.any? {|goal| goal.hidden == true} %>
    <h3>My Private Goals</h3>
    <% @users_goals.each do |goal| %>
      <% next if goal.hidden == false %>
      <%= render "goal_guts", goal: goal %>
      <%= render "buttons", goal: goal %>
    <% end %>
  <% end %>
  <br>
    <%= link_to "Set a New Goal", new_goal_url %>
<% end %>

<br>
<br>